# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Product.create( bhproduct_number:96999, name:"Aprons - Boars Head")
Product.create( bhproduct_number:95970, name:"Hats - Boars Head")
Product.create( bhproduct_number:90195, name:"Deli Wrap Paper")
Product.create( bhproduct_number:50063, name:"PS BNLS SMKD HAM ST")
Product.create( bhproduct_number:50040, name:"PRE-SLICED BEEF BOL")
Product.create( bhproduct_number:50037, name:"Prosc. Di Parma- Pr")
Product.create( bhproduct_number:50030, name:"PRE-SLICED BOLOGNA")
Product.create( bhproduct_number:50026, name:"PRE-SLICED SMOKED H")
Product.create( bhproduct_number:50024, name:"PRE-SLICED HONEY SM")
Product.create( bhproduct_number:50018, name:"PRE-SLICED MORTADEL")
Product.create( bhproduct_number:50016, name:"PRE-SLICED SOPRESSA")
Product.create( bhproduct_number:50012, name:"PRE-SLICED WHITE AM")
Product.create( bhproduct_number:50011, name:"PRE-SLICED PEPPER J")
Product.create( bhproduct_number:50009, name:"PRE-SLICED VT CHEDD")
Product.create( bhproduct_number:50007, name:"PRE-SLICED LS PROVO")
Product.create( bhproduct_number:50003, name:"Pre-Sliced Gold Swi")
Product.create( bhproduct_number:50002, name:"Pre-Sliced Hard Sal")
Product.create( bhproduct_number:50001, name:"Pre-Sliced American")
Product.create( bhproduct_number:16198, name:"Turkey Chili w/Be")
Product.create( bhproduct_number:16189, name:"SUP ITAL DRY SSGE D")
Product.create( bhproduct_number:16187, name:"FS RED PEPPER HUMMU")
Product.create( bhproduct_number:16186, name:"FS AN CHIPTL PPR HU")
Product.create( bhproduct_number:16185, name:"FS TRADITIONAL HUMM")
Product.create( bhproduct_number:16167, name:"RSTD RED PPR HUM &")
Product.create( bhproduct_number:16163, name:"CHIPOTLE HUMMUS W/G")
Product.create( bhproduct_number:16162, name:"ROASTED RED PEPPER")
Product.create( bhproduct_number:16161, name:"ALL NATURAL GARLIC")
Product.create( bhproduct_number:16160, name:"ROASTED PINE NUT HU")
Product.create( bhproduct_number:16159, name:"ALL NATURAL HUMMUS")
Product.create( bhproduct_number:16158, name:"AN TRAD HUMMUS & PR")
Product.create( bhproduct_number:16154, name:"Pouch Pepperoni Trk")
Product.create( bhproduct_number:16136, name:"GOURMAISE 32 OZ")
Product.create( bhproduct_number:16135, name:"Pepperhouse Dressin")
Product.create( bhproduct_number:16133, name:"Chipotle Mayo FS qu")
Product.create( bhproduct_number:16132, name:"Squeese Chipotle Ma")
Product.create( bhproduct_number:16129, name:"BEEF VEGETABLE SOUP")
Product.create( bhproduct_number:16128, name:"TOMATO BASIL SOUP")
Product.create( bhproduct_number:16125, name:"HORSRDISH PKLE CHIP")
Product.create( bhproduct_number:16119, name:"SPLIT PEA SOUP")
Product.create( bhproduct_number:16118, name:"Turkey & Roasted Co")
Product.create( bhproduct_number:16113, name:"CHORIZO ESPANOL")
Product.create( bhproduct_number:16093, name:"PEPPERED SALAME 8OZ")
Product.create( bhproduct_number:16090, name:"Chicken Pot Pie")
Product.create( bhproduct_number:16087, name:"Real Mayo Sq.")
Product.create( bhproduct_number:16085, name:"Mayo. BH 4 Gallon T")
Product.create( bhproduct_number:16078, name:"Pepperoni Stick")
Product.create( bhproduct_number:16071, name:"Salame Panino")
Product.create( bhproduct_number:16070, name:"INSALATA PANINO NET")
Product.create( bhproduct_number:16069, name:"Italian Dry Sausage")
Product.create( bhproduct_number:16067, name:"Genoa Mini")
Product.create( bhproduct_number:16064, name:"Sopressata Mini PC")
Product.create( bhproduct_number:16062, name:"Sweet Soppressata M")
Product.create( bhproduct_number:16060, name:"Squeeze BBQ Mild")
Product.create( bhproduct_number:16058, name:"Mayo Boar's Head Gl")
Product.create( bhproduct_number:16057, name:"GENOA SALAME - 9 OZ")
Product.create( bhproduct_number:16031, name:"Sauerkraut - 5gl")
Product.create( bhproduct_number:16030, name:"Bianco D'Oro Salam")
Product.create( bhproduct_number:16028, name:"Cajun Remoulade")
Product.create( bhproduct_number:16024, name:"Half Sour Pickles")
Product.create( bhproduct_number:16020, name:"Chicken Tortilla So")
Product.create( bhproduct_number:16019, name:"ANTI GENOA & PROVOL")
Product.create( bhproduct_number:16018, name:"ANTI SOPRE & PROVO")
Product.create( bhproduct_number:16012, name:"Manhattan Clam Chow")
Product.create( bhproduct_number:16011, name:"New England Clam Ch")
Product.create( bhproduct_number:16010, name:"Minestrone Soup")
Product.create( bhproduct_number:16008, name:"Chicken Noodle Soup")
Product.create( bhproduct_number:16006, name:"Ground Beef Chile w")
Product.create( bhproduct_number:16004, name:"Turkey w/White & Wi")
Product.create( bhproduct_number:16003, name:"Squeeze Horse Sauce")
Product.create( bhproduct_number:16002, name:"Squeeze Honey Musta")
Product.create( bhproduct_number:16001, name:"Squeeze Mustard")
Product.create( bhproduct_number:15158, name:"MarBlue - Marbled B")
Product.create( bhproduct_number:15153, name:"Mozzarella w/Italia")
Product.create( bhproduct_number:15152, name:"Mozzarella W Italia")
Product.create( bhproduct_number:15138, name:"FS Fresh Mozz Ovoli")
Product.create( bhproduct_number:15133, name:"FS Fresh Mozz Celin")
Product.create( bhproduct_number:15120, name:"Mozz Whole Milk Shr")
Product.create( bhproduct_number:15071, name:"3 Pepper Colby Jack")
Product.create( bhproduct_number:15070, name:"Chipolte Gouda PC")
Product.create( bhproduct_number:15062, name:"Pre Cut Smoked Goud")
Product.create( bhproduct_number:15061, name:"3 Pepper Colby Jack")
Product.create( bhproduct_number:15060, name:"Chipotle Gouda Chee")
Product.create( bhproduct_number:15054, name:"BRIE CHEESE WHEEL")
Product.create( bhproduct_number:15045, name:"PC Aged Gouda Chees")
Product.create( bhproduct_number:15041, name:"GOAT CHEESE 4OZ RET")
Product.create( bhproduct_number:15035, name:"Smoked Gouda")
Product.create( bhproduct_number:15033, name:"Fratelli Peccorino")
Product.create( bhproduct_number:15026, name:"French Gruyere")
Product.create( bhproduct_number:15025, name:"GOUDA CHEESE LOAF")
Product.create( bhproduct_number:15010, name:"Asiago")
Product.create( bhproduct_number:15008, name:"Bulk Crumbled Gorgo")
Product.create( bhproduct_number:15007, name:"Bulk Feta Crumbled")
Product.create( bhproduct_number:15006, name:"Bulk Blue Cheese Cr")
Product.create( bhproduct_number:14003, name:"Beef Franks Sknls")
Product.create( bhproduct_number:13044, name:"Ichiban Teriyaki Ch")
Product.create( bhproduct_number:13043, name:"Jerk Chicken Breast")
Product.create( bhproduct_number:13034, name:"Chipotle Chicken")
Product.create( bhproduct_number:13033, name:"Blackened Turkey")
Product.create( bhproduct_number:13024, name:"FS Ready to Serve T")
Product.create( bhproduct_number:13018, name:"NSA Turkey Breast")
Product.create( bhproduct_number:13016, name:"Jerk Turkey")
Product.create( bhproduct_number:13014, name:"Everroast Chicken B")
Product.create( bhproduct_number:13013, name:"All American BBQ")
Product.create( bhproduct_number:13005, name:"BUFFALO AN TKY JERK")
Product.create( bhproduct_number:12017, name:"Roast Beef Top Roun")
Product.create( bhproduct_number:12015, name:"Roast Beef Top Rnd")
Product.create( bhproduct_number:12012, name:"Mesquite Beef Brisk")
Product.create( bhproduct_number:12011, name:"London Broil")
Product.create( bhproduct_number:12006, name:"Roast Beef")
Product.create( bhproduct_number:12002, name:"LONDON BROIL AN BF")
Product.create( bhproduct_number:11046, name:"Nat Smked Bacon Thk")
Product.create( bhproduct_number:11044, name:"Peppenero Garlic Ha")
Product.create( bhproduct_number:11038, name:"APPLEWOOD SPIRAL HA")
Product.create( bhproduct_number:11014, name:"BF BEECHWOOD SMKD H")
Product.create( bhproduct_number:11005, name:"BF BEECHWOOD SMKD H")
Product.create( bhproduct_number:11003, name:"FS Applewood Smoked")
Product.create( bhproduct_number:11002, name:"Hamcraft Ham")
Product.create( bhproduct_number:8779, name:"1/2 GAL. Pub Horse")
Product.create( bhproduct_number:8738, name:"1/2 Gal. Honey Must")
Product.create( bhproduct_number:1805, name:"Sandwich Stickers -")
Product.create( bhproduct_number:1664, name:"Salad - Cranberry C")
Product.create( bhproduct_number:1661, name:"Pre-Sliced LOL Yell")
Product.create( bhproduct_number:1648, name:"LOL White Amer Chee")
Product.create( bhproduct_number:1644, name:"Butter- 1LB Unsalte")
Product.create( bhproduct_number:1643, name:"Chicken - Grld NS P")
Product.create( bhproduct_number:1640, name:"Burgers - Turkey")
Product.create( bhproduct_number:1637, name:"Wrap - Whole Wheat")
Product.create( bhproduct_number:1632, name:"Peppers - Banana")
Product.create( bhproduct_number:1631, name:"Peppers - Sweet")
Product.create( bhproduct_number:1630, name:"Peppers - Hot")
Product.create( bhproduct_number:1629, name:"Vinegar Viva Ital S")
Product.create( bhproduct_number:1628, name:"Shredded Parmigiana")
Product.create( bhproduct_number:1627, name:"Northside Pre Ck Ba")
Product.create( bhproduct_number:1626, name:"Tyson 944 Chicken")
Product.create( bhproduct_number:1625, name:"Oil - Blended 10%")
Product.create( bhproduct_number:1619, name:"Chicken - Grld NS T")
Product.create( bhproduct_number:1616, name:"Chicken - Grld NS L")
Product.create( bhproduct_number:1614, name:"Harvest Raspberry C")
Product.create( bhproduct_number:1613, name:"Soup Suprm- Vegetab")
Product.create( bhproduct_number:1610, name:"Soup Suprm- Cheddar")
Product.create( bhproduct_number:1598, name:"Nova Board")
Product.create( bhproduct_number:1594, name:"Tyson Red Label Gri")
Product.create( bhproduct_number:1593, name:"Health Salad")
Product.create( bhproduct_number:1576, name:"Harvest Chocolate C")
Product.create( bhproduct_number:1575, name:"Harvest - Carrot Ca")
Product.create( bhproduct_number:1574, name:"Harvest Apple Caram")
Product.create( bhproduct_number:1571, name:"Salad - Tortellini")
Product.create( bhproduct_number:1568, name:"Salad - Mushroom")
Product.create( bhproduct_number:1567, name:"Salad  Olive 5 lb.")
Product.create( bhproduct_number:1565, name:"Cream Cheese 50lb P")
Product.create( bhproduct_number:1561, name:"Harvest - Asstd Cup")
Product.create( bhproduct_number:1560, name:"Harvest - Asstd Cup")
Product.create( bhproduct_number:1559, name:"Olives - Black- Sli")
Product.create( bhproduct_number:1553, name:"Harvest Crumb Cake")
Product.create( bhproduct_number:1552, name:"Salad - Tuna")
Product.create( bhproduct_number:1549, name:"Egg Salad")
Product.create( bhproduct_number:1545, name:"Harvest- Oreo Cake")
Product.create( bhproduct_number:1540, name:"Salad - Cole Slaw")
Product.create( bhproduct_number:1538, name:"Salad - Rotini Past")
Product.create( bhproduct_number:1535, name:"Salad - Italian Sea")
Product.create( bhproduct_number:1533, name:"Wrap - Spinich Alla")
Product.create( bhproduct_number:1532, name:"Cheese Steaks - 8oz")
Product.create( bhproduct_number:1531, name:"Wrap Plain")
Product.create( bhproduct_number:1529, name:"Chicken - Grilled T")
Product.create( bhproduct_number:1528, name:"Hatfield Porkroll")
Product.create( bhproduct_number:1525, name:"Cheese Steaks - 5oz")
Product.create( bhproduct_number:1524, name:"Rice Pudding 8lb")
Product.create( bhproduct_number:1523, name:"Chicken Cheese Stea")
Product.create( bhproduct_number:1517, name:"Meatballs")
Product.create( bhproduct_number:1516, name:"Salad - Chicken")
Product.create( bhproduct_number:1515, name:"Salad  - Red Skin Po")
Product.create( bhproduct_number:1514, name:"Tuna White")
Product.create( bhproduct_number:1513, name:"Salad - Potato 5 lb")
Product.create( bhproduct_number:1511, name:"Salad - Seafood")
Product.create( bhproduct_number:1509, name:"Crab Cakes - Fully")
Product.create( bhproduct_number:1507, name:"Butter- Hotel Bar W")
Product.create( bhproduct_number:1502, name:"Salad - Shrimp")
Product.create( bhproduct_number:1501, name:"Salad - Macaroni")
Product.create( bhproduct_number:1339, name:"Salad- Buffalo Chic")
Product.create( bhproduct_number:1111, name:"Nutrition Guides")
Product.create( bhproduct_number:999, name:"Misc Item")
Product.create( bhproduct_number:998, name:"Returned Check Fee")
Product.create( bhproduct_number:985, name:"P/C Imported Swiss")
Product.create( bhproduct_number:983, name:"P/C Picante Provolo")
Product.create( bhproduct_number:981, name:"P/C Muenster")
Product.create( bhproduct_number:980, name:"P/C Pepper Jack Che")
Product.create( bhproduct_number:978, name:"P/C Jalapeno Havart")
Product.create( bhproduct_number:977, name:"P/C Dill Havarti")
Product.create( bhproduct_number:976, name:"P/C Plain Havarti")
Product.create( bhproduct_number:973, name:"P/C Imported Gouda")
Product.create( bhproduct_number:972, name:"P/C Fontina Cheese")
Product.create( bhproduct_number:971, name:"P/C Feta Cheese")
Product.create( bhproduct_number:966, name:"P/C Horseradish Che")
Product.create( bhproduct_number:963, name:"P/C Blk Wax Cheddar")
Product.create( bhproduct_number:961, name:"P/C Butterkase")
Product.create( bhproduct_number:960, name:"P/C Blue Cheese")
Product.create( bhproduct_number:957, name:"Jar Ham Glaze")
Product.create( bhproduct_number:956, name:"Jar Vidalia Onions")
Product.create( bhproduct_number:940, name:"Fresh Burgers 2-1-")
Product.create( bhproduct_number:932, name:"Crumbled Feta Chees")
Product.create( bhproduct_number:931, name:"Crumbled Gorgonzola")
Product.create( bhproduct_number:930, name:"Crumbled Blue Chees")
Product.create( bhproduct_number:913, name:"Ground Beef")
Product.create( bhproduct_number:905, name:"Hamburger 3/1")
Product.create( bhproduct_number:896, name:"Jar Jalapeno Pepper")
Product.create( bhproduct_number:859, name:"Grated Parmesan Che")
Product.create( bhproduct_number:846, name:"Parmesan Reggiano P")
Product.create( bhproduct_number:815, name:"160 Ct Pickles")
Product.create( bhproduct_number:798, name:"5 Gal. Pickle Chips")
Product.create( bhproduct_number:796, name:"5 Gal. Spear Pickle")
Product.create( bhproduct_number:795, name:"5 Gal. Garlic Pickl")
Product.create( bhproduct_number:788, name:"Deli Dressing")
Product.create( bhproduct_number:757, name:"Fontina Cheese")
Product.create( bhproduct_number:751, name:"Pepper Jack Cheese")
Product.create( bhproduct_number:750, name:"Monterey Jack Chees")
Product.create( bhproduct_number:748, name:"Feta Cheese Pail")
Product.create( bhproduct_number:740, name:"Gallon Mustard")
Product.create( bhproduct_number:731, name:"1 LB. Sauerkraut")
Product.create( bhproduct_number:727, name:"Jalapeno Havarti 1/")
Product.create( bhproduct_number:725, name:"Plain Havarti - 1/2")
Product.create( bhproduct_number:713, name:"L/S American Cheese")
Product.create( bhproduct_number:712, name:"L/S American Cheese")
Product.create( bhproduct_number:711, name:"Prosciutto di Parma")
Product.create( bhproduct_number:704, name:"L/S Muenster")
Product.create( bhproduct_number:700, name:"1/2 Colby Jack")
Product.create( bhproduct_number:689, name:"Cream Cheese- BH")
Product.create( bhproduct_number:683, name:"Imp Gold Swiss 1/2")
Product.create( bhproduct_number:682, name:"IMP GLD SWISS 4X4")
Product.create( bhproduct_number:674, name:"3LB Cream Cheese Bl")
Product.create( bhproduct_number:672, name:"Baby Swiss")
Product.create( bhproduct_number:671, name:"5LB. Cream Cheese T")
Product.create( bhproduct_number:670, name:"Lacey Swiss")
Product.create( bhproduct_number:668, name:"BH Provolone")
Product.create( bhproduct_number:666, name:"Blk Wax Cheddar")
Product.create( bhproduct_number:664, name:"Domestic Swiss 1/2")
Product.create( bhproduct_number:663, name:"Domestic Swiss 4x4")
Product.create( bhproduct_number:654, name:"Muenster")
Product.create( bhproduct_number:653, name:"White American Chee")
Product.create( bhproduct_number:652, name:"Yellow American Che")
Product.create( bhproduct_number:649, name:"Swiss No Salt")
Product.create( bhproduct_number:648, name:"Picante Provolone")
Product.create( bhproduct_number:647, name:"Pre-Sliced White Am")
Product.create( bhproduct_number:644, name:"Pre-Sliced Yellow A")
Product.create( bhproduct_number:629, name:"Yellow Vermont Ched")
Product.create( bhproduct_number:628, name:"Wht Vermont Cheddar")
Product.create( bhproduct_number:627, name:"Horseradish Cheese")
Product.create( bhproduct_number:620, name:"Mozzarella Loaf - B")
Product.create( bhproduct_number:597, name:"Soppressata SWT")
Product.create( bhproduct_number:596, name:"1/2 Hot Sopressata")
Product.create( bhproduct_number:595, name:"Pouch Pepperoni - P")
Product.create( bhproduct_number:569, name:"Trenton Pork Roll")
Product.create( bhproduct_number:557, name:"Hard Salami 1/2")
Product.create( bhproduct_number:551, name:"Whole Genoa Salami")
Product.create( bhproduct_number:547, name:"Genoa Salami")
Product.create( bhproduct_number:540, name:"Layered Bacon - Can")
Product.create( bhproduct_number:539, name:"Layer Bacon")
Product.create( bhproduct_number:538, name:"Domestic Bacon 1lb")
Product.create( bhproduct_number:536, name:"Domestic Layout Bac")
Product.create( bhproduct_number:533, name:"Pre-Cooked Bacon")
Product.create( bhproduct_number:532, name:"Grande Pepperoni")
Product.create( bhproduct_number:531, name:"Skinless Shankless")
Product.create( bhproduct_number:530, name:"Piccolo Prosciutto")
Product.create( bhproduct_number:527, name:"Sliced Pepperoni #3")
Product.create( bhproduct_number:511, name:"Mortadella Small w/")
Product.create( bhproduct_number:508, name:"Mortadella AB w/ Pi")
Product.create( bhproduct_number:505, name:"Di Landri Genoa")
Product.create( bhproduct_number:503, name:"Capocollo Sweet")
Product.create( bhproduct_number:502, name:"Capocollo Hot")
Product.create( bhproduct_number:500, name:"Boneless Prosciutto")
Product.create( bhproduct_number:485, name:"Jar Horse Pickle Ch")
Product.create( bhproduct_number:484, name:"N/C P&B Franks Reta")
Product.create( bhproduct_number:450, name:"Breakfast Sausage")
Product.create( bhproduct_number:447, name:"64 oz Savory Cajun")
Product.create( bhproduct_number:442, name:"1/2 Virginia Brand")
Product.create( bhproduct_number:441, name:"Golden Catering Tur")
Product.create( bhproduct_number:440, name:"Blazin' Buffalo Chi")
Product.create( bhproduct_number:439, name:"Lemon Pepper Chicke")
Product.create( bhproduct_number:437, name:"Classic Chicken")
Product.create( bhproduct_number:436, name:"N/C 8/1 Lite Beef F")
Product.create( bhproduct_number:435, name:"N/C 8/1 Beef Franks")
Product.create( bhproduct_number:432, name:"Skin-On L/S Turkey")
Product.create( bhproduct_number:421, name:"Skinless L/S Turkey")
Product.create( bhproduct_number:417, name:"Cocktail Franks")
Product.create( bhproduct_number:415, name:"Beef Franks 4/1")
Product.create( bhproduct_number:410, name:"Knockwurst 1LB")
Product.create( bhproduct_number:400, name:"Pork Shoulder Butt")
Product.create( bhproduct_number:399, name:"Bratwurst 1LB")
Product.create( bhproduct_number:368, name:"Liverwurst - N/C")
Product.create( bhproduct_number:360, name:"Oval Spiced Ham 1/2")
Product.create( bhproduct_number:358, name:"Beef Bologna")
Product.create( bhproduct_number:357, name:"Lower Sodium Bologn")
Product.create( bhproduct_number:354, name:"Garlic Bologna")
Product.create( bhproduct_number:342, name:"Lite Liverwurst")
Product.create( bhproduct_number:341, name:"Pastrami Navel")
Product.create( bhproduct_number:340, name:"Pastrami Round")
Product.create( bhproduct_number:337, name:"Beef Franks N/C Bul")
Product.create( bhproduct_number:336, name:"BH Slab Bacon")
Product.create( bhproduct_number:331, name:"Kielbasa")
Product.create( bhproduct_number:327, name:"Beef Salami")
Product.create( bhproduct_number:325, name:"Cooked Salami")
Product.create( bhproduct_number:321, name:"Bologna Wide")
Product.create( bhproduct_number:320, name:"Bologna 1/2")
Product.create( bhproduct_number:314, name:"Strass Liverwurst")
Product.create( bhproduct_number:310, name:"Spiced Ham")
Product.create( bhproduct_number:308, name:"Pick & Pepp Loaf")
Product.create( bhproduct_number:306, name:"Olive Loaf")
Product.create( bhproduct_number:303, name:"Head Cheese")
Product.create( bhproduct_number:296, name:"Cajun Turkey")
Product.create( bhproduct_number:294, name:"Mesquite Turkey")
Product.create( bhproduct_number:284, name:"Salsalito Turkey")
Product.create( bhproduct_number:278, name:"Ovengold Turkey")
Product.create( bhproduct_number:276, name:"Cracked Pepper Turk")
Product.create( bhproduct_number:275, name:"Pastrami Turkey")
Product.create( bhproduct_number:270, name:"Maple Honey Turkey")
Product.create( bhproduct_number:265, name:"Split Fresh Beef To")
Product.create( bhproduct_number:238, name:"Red Pastrami Round")
Product.create( bhproduct_number:225, name:"Corned Beef Nat")
Product.create( bhproduct_number:223, name:"Choice C.B. Brisket")
Product.create( bhproduct_number:211, name:"Raw C.B. 1st Cut")
Product.create( bhproduct_number:210, name:"Pastrami 1st Cut")
Product.create( bhproduct_number:206, name:"C.B. 1st Cut")
Product.create( bhproduct_number:201, name:"NSA Cooked Roast B")
Product.create( bhproduct_number:182, name:"Baby Sweet Slice 1/")
Product.create( bhproduct_number:173, name:"Rosemary Ham")
Product.create( bhproduct_number:171, name:"Red Hot Ham Cappy")
Product.create( bhproduct_number:161, name:"Fresh Ham 1/2")
Product.create( bhproduct_number:159, name:"Low Salt Ham 1/2")
Product.create( bhproduct_number:158, name:"Tavern Ham 1/2")
Product.create( bhproduct_number:156, name:"Virginia Ham - Smok")
Product.create( bhproduct_number:153, name:"Sweet Slice Ham 1/2")
Product.create( bhproduct_number:152, name:"Whole Sweet Slice H")
Product.create( bhproduct_number:151, name:"Maple Honey Ham 1/2")
Product.create( bhproduct_number:150, name:"Maple Honey Ham")
Product.create( bhproduct_number:140, name:"Gourmet Pepper Ham")
Product.create( bhproduct_number:139, name:"Pepper Ham")
Product.create( bhproduct_number:134, name:"Ham Cappy 1/2")
Product.create( bhproduct_number:114, name:"Virginia Ham")
Product.create( bhproduct_number:106, name:"Deluxe Ham Round To")
Product.create( bhproduct_number:105, name:"Low Salt Ham")
Product.create( bhproduct_number:103, name:"Deluxe Ham Lg Baby")